spring.application.name=CCMS2.0

# MySql database configuration
spring.datasource.url = jdbc:mysql://localhost:3306/ccms2
spring.datasource.username = root
spring.datasource.password = Sandeep@123

# JPA configuration
spring.jpa.show-sql=true
# For creating schemas and tables
spring.jpa.hibernate.ddl-auto=update 

# Email configuration


# spring security setup (When we add spring-security starter there is by default login page)
# spring.security.user.name=user
# spring.security.user.password=user